import assert from "node:assert/strict";
import { advanceEscape, CYCLE_MS, escapeScore, exposeEscape, FINISH, hiddenAt, initialProgress, inputEscape, parseProgress, phaseAt } from "../../src/games/typing-escape/model.ts";

const start = 1_000_000;
assert.equal(phaseAt(null, start).active, false);
assert.equal(phaseAt(start, start - 1).active, false);
assert.equal(phaseAt(start, start).syllable, 0);
assert.equal(phaseAt(start, start + 7_199).watching, false);
assert.equal(phaseAt(start, start + 7_200).watching, true);
assert.equal(phaseAt(start, start + CYCLE_MS).watching, false);
let state = inputEscape(initialProgress(), "cat", "c", start, start + 100);
assert.equal(state.distance, 1);
assert.equal(hiddenAt(state, start + 379), false);
assert.equal(hiddenAt(state, start + 380), true);
state = inputEscape(state, "cat", "cx", start, start + 200);
assert.equal(state.distance, 1, "wrong letters never move");
state = inputEscape(state, "cat", "", start, start + 300);
state = inputEscape(state, "cat", "c", start, start + 400);
assert.equal(state.distance, 1, "deleting and retyping does not farm movement");
state = inputEscape(state, "cat", "cat", start, start + 500);
assert.equal(state.distance, 3);
assert.equal(state.question, 1);
assert.equal(state.input, "");
assert.equal(state.prefix, 0);
const exposed = { ...state, distance: 40, best: 40, lastInputAt: start + 7_000 };
const hit = advanceEscape(exposed, start, start + 7_200);
assert.equal(hit.distance, 25);
assert.equal(advanceEscape(hit, start, start + 7_300).distance, 25, "only one penalty per cycle");
assert.equal(advanceEscape(exposed, start, start + 30_000).distance, 25, "background tabs still resolve the missed shot");
assert.equal(advanceEscape({ ...exposed, lastInputAt: start + 6_900 }, start, start + 7_200).distance, 40);
const redInput = exposeEscape({ ...exposed, lastInputAt: start + 6_000 }, start, start + 7_300);
assert.equal(redInput.distance, 25, "even IME and incorrect keystrokes during red trigger a hit");
assert.equal(inputEscape(redInput, "cat", "c", start, start + 7_400).distance, 25);
assert.equal(inputEscape(initialProgress(), "가나", "ㄱ", start, start + 100).distance, 0);
assert.equal(inputEscape(initialProgress(), "가나", "가", start, start + 100).distance, 1);
assert.equal(inputEscape(initialProgress(), "cat", "c", null, start).distance, 0);
const finished = inputEscape({ ...initialProgress(), distance: FINISH - 1, best: FINISH - 1 }, "cat", "c", start, start + 100);
assert.equal(finished.distance, FINISH);
assert.ok(escapeScore(finished) > escapeScore({ ...finished, finishedElapsed: 500 }), "earlier finish wins");
assert.ok(escapeScore({ ...finished, finishedElapsed: 999_999 }) > FINISH, "finishers always outrank unfinished players");
assert.equal(exposeEscape(finished, start, start + 7_300).distance, FINISH);
assert.deepEqual(parseProgress({ ...state, distance: NaN }), initialProgress());
assert.deepEqual(parseProgress({ ...state, question: -1 }), initialProgress());
assert.deepEqual(parseProgress(state), state);
console.log("typing escape timing, hiding, penalty, IME, progress and recovery tests passed");
