import assert from "node:assert/strict";
import { advanceEscape, chantForCycle, CYCLE_MS, DEATH_MS, ESCAPE_POINTS, escapeScore, escapeTypingState, exposeEscape, FINISH, hiddenAt, HIDE_MS, initialProgress, inputEscape, parseProgress, phaseAt, RESPAWN_MS, STEP, WORD_JUMP } from "../../src/games/typing-escape/model.ts";

const start = 1_000_000;
assert.equal(phaseAt(null, start).active, false);
assert.equal(phaseAt(start, start - 1).active, false);
assert.equal(phaseAt(start, start).syllable, 0);
const plans = Array.from({ length: 50 }, (_, cycle) => chantForCycle(start, cycle));
assert.ok(new Set(plans.map(plan => plan.shotOffset)).size > 40, "shot timing must vary every chant");
assert.ok(plans.some(plan => plan.beats.length > 10), "the guard stutters and repeats syllables");
assert.ok(plans.some(plan => Math.max(...plan.beats.map(beat => beat.duration)) > 600), "long pauses bait the runner");
assert.ok(plans.some(plan => Math.min(...plan.beats.map(beat => beat.duration)) < 180), "rapid bursts are unpredictable");
plans.forEach((plan, cycle) => {
  assert.deepEqual(chantForCycle(start, cycle), plan, "all clients share the same chant");
  assert.ok(plan.shotOffset > 2_000 && plan.shotOffset < CYCLE_MS - 1_000);
  const shotAt = start + cycle * CYCLE_MS + plan.shotOffset;
  assert.equal(phaseAt(start, shotAt - 1).watching, false);
  assert.equal(phaseAt(start, shotAt).watching, true);
  assert.equal(phaseAt(start, start + (cycle + 1) * CYCLE_MS).watching, false);
  plan.beats.forEach((beat, index) => assert.equal(phaseAt(start, start + cycle * CYCLE_MS + beat.at).beat, index));
});
assert.notDeepEqual(chantForCycle(start + 1, 0), plans[0]);

let state = inputEscape(initialProgress(), "cat", "c", start, start + 100);
assert.equal(state.distance, STEP, "one correct key makes a visible step");
assert.equal(hiddenAt(state, start + 100 + HIDE_MS - 1), false);
assert.equal(hiddenAt(state, start + 100 + HIDE_MS), true);
state = inputEscape(state, "cat", "cx", start, start + 200);
assert.equal(state.distance, STEP, "wrong letters never move");
state = inputEscape(state, "cat", "", start, start + 300);
state = inputEscape(state, "cat", "c", start, start + 400);
assert.equal(state.distance, STEP, "deleting and retyping cannot farm movement");
state = inputEscape(state, "cat", "cat", start, start + 500);
assert.equal(state.distance, STEP * 3 + WORD_JUMP, "completing a word leaps forward");
assert.ok(state.completedUntil > start + 500);
assert.equal(state.question, 1);
assert.equal(state.input, "");
assert.equal(state.strokes, 0);

let korean = initialProgress();
for (const [value, strokes] of [["ㅎ", 1], ["하", 2], ["한", 3], ["한ㄱ", 4], ["한그", 5], ["한글", 6]] as const) {
  korean = inputEscape(korean, "한글", value, start, start + strokes * 60, true);
  assert.equal(korean.distance, strokes * STEP, "each correct Korean IME keystroke moves immediately");
  assert.equal(korean.question, 0, "don't switch prompts while the IME is composing");
}
korean = inputEscape(korean, "한글", "한글", start, start + 400);
assert.equal(korean.distance, STEP * 6 + WORD_JUMP);
assert.equal(korean.question, 1);
assert.equal(korean.input, "");
assert.equal(escapeTypingState("과", "고").strokes, 2);
assert.equal(escapeTypingState("과", "과").strokes, 3);
assert.equal(escapeTypingState("가나", "간").strokes, 3, "IME moves final consonants into the next syllable");
assert.equal(escapeTypingState("한글", "하").hasError, false);
assert.equal(escapeTypingState("한글", "핳").hasError, true);
assert.equal(escapeTypingState("“Run!”", '"Run!"').hasError, false, "typing uses the existing punctuation normalization");
assert.equal(inputEscape(initialProgress(), "cat", "c", null, start).distance, 0);
assert.equal(escapeTypingState("Hello, World!", "hello world", { ignoreCase: true, ignorePunctuation: true }).isComplete, true, "lobby options reuse the typing game's comparison");
assert.equal(escapeTypingState("Hello, World!", "hello world").isComplete, false);
assert.equal(escapeTypingState("Hi!", "h", { ignoreCase: true }).strokes, 1);

const shotAt = phaseAt(start, start).shotAt;
const exposed = { ...state, distance: 80, lastInputAt: shotAt - 100 };
const hit = advanceEscape({ ...exposed, input: "ca", strokes: 2 }, start, shotAt);
assert.equal(hit.distance, 80, "a shot runner stays where they fell during the countdown");
assert.equal(hit.stunnedUntil, shotAt + DEATH_MS);
assert.equal(hiddenAt(hit, shotAt + DEATH_MS - 1), true);
const respawned = advanceEscape(hit, start, shotAt + DEATH_MS);
assert.equal(respawned.distance, 0, "the countdown ends back at the start");
assert.equal(respawned.hits, 1);
assert.equal(respawned.lastInputAt, 0);
assert.equal(inputEscape(respawned, "cat", "c", start, start + CYCLE_MS + 100).distance, STEP, "typing resumes after the countdown");
assert.equal(hit.input, "", "a hit erases the typed answer");
assert.equal(hit.strokes, 0);
assert.equal(hit.hits, 1);
assert.equal(advanceEscape(hit, start, shotAt + 100).hits, 1, "one penalty per watch phase");
assert.equal(advanceEscape(exposed, start, start + 30_000).hits, 1, "sleeping tabs still resolve missed shots");
assert.equal(advanceEscape({ ...exposed, lastInputAt: shotAt - HIDE_MS }, start, shotAt).distance, 80);
assert.equal(exposeEscape({ ...exposed, lastInputAt: shotAt - 500 }, start, shotAt + 100).hits, 1, "incorrect and IME keydowns during red also get caught");
assert.equal(inputEscape(hit, "cat", "c", start, shotAt + 200).input, "", "the countdown cannot be bypassed by typing");
const redInput = inputEscape({ ...initialProgress(), input: "c", strokes: 1, distance: STEP }, "cat", "ca", start, shotAt + 100);
assert.equal(redInput.hits, 1);
assert.equal(advanceEscape(redInput, start, shotAt + 100 + DEATH_MS).distance, 0);
assert.equal(redInput.input, "", "typing while watched is shot and erased");

const finished = inputEscape({ ...initialProgress(), distance: FINISH - STEP, input: "c", strokes: 1 }, "cat", "ca", start, start + 100);
assert.equal(finished.distance, 0, "escaping starts the next lap at once");
assert.equal(finished.escapes, 1);
assert.equal(finished.escapedUntil, start + 100 + RESPAWN_MS);
assert.equal(escapeScore(finished), ESCAPE_POINTS);
assert.equal(finished.input, "ca", "escaping keeps the half-typed word");
const keepTyping = inputEscape(finished, "cat", "cat", start, start + 200);
assert.equal(keepTyping.escapes, 1, "typing right after an escape never stalls or scores twice");
assert.equal(keepTyping.distance, STEP + WORD_JUMP);
assert.equal(keepTyping.question, 1);
const leapOut = inputEscape({ ...initialProgress(), distance: 60, input: "ca", strokes: 2 }, "cat", "cat", start, start + 100);
assert.equal(leapOut.escapes, 1, "a completion leap can carry the runner out");
assert.equal(leapOut.distance, 0);
assert.equal(leapOut.question, 1);
const closeEscape = inputEscape({ ...initialProgress(), distance: FINISH - STEP }, "cat", "c", start, shotAt - 20);
assert.equal(closeEscape.lastInputAt, 0);
assert.equal(advanceEscape(closeEscape, start, shotAt + 100).hits, 0, "a completed escape protects the next lap from its old shot");
assert.equal(escapeScore(exposeEscape({ ...finished, distance: 80 }, start, shotAt + 100)), ESCAPE_POINTS, "a death preserves completed-lap points");
const imeExit = inputEscape({ ...initialProgress(), distance: FINISH - STEP }, "가", "가", start, start + 100, true);
assert.equal(imeExit.escapes, 1);
assert.equal(inputEscape(imeExit, "가", "가", start, start + 200).question, 1, "IME commits right after an escape");

assert.deepEqual(parseProgress({ ...state, distance: NaN }), initialProgress());
assert.deepEqual(parseProgress({ ...state, question: -1 }), initialProgress());
assert.deepEqual(parseProgress({ ...state, hits: 1.5 }), initialProgress());
assert.deepEqual(parseProgress({ ...state, distance: FINISH }), initialProgress());
assert.deepEqual(parseProgress(state), state);
assert.deepEqual(parseProgress({ ...keepTyping, unexpected: "untrusted" }), keepTyping);
console.log("typing escape: unpredictable shared chants, per-key IME movement, completion leaps, hiding, deaths that erase input and seamless escapes passed");
